/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lengyue524_opus_OpusEncoder */

#ifndef _Included_com_lengyue524_opus_OpusEncoder
#define _Included_com_lengyue524_opus_OpusEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lengyue524_opus_OpusEncoder
 * Method:    init_voip_native
 * Signature: (II)I
 */
JNIEXPORT jlong JNICALL Java_com_lengyue524_opus_OpusEncoder_init_1voip_1native
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lengyue524_opus_OpusEncoder
 * Method:    init_audio_native
 * Signature: (II)I
 */
JNIEXPORT jlong JNICALL Java_com_lengyue524_opus_OpusEncoder_init_1audio_1native
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lengyue524_opus_OpusEncoder
 * Method:    init_restricted_low_delay_native
 * Signature: (II)I
 */
JNIEXPORT jlong JNICALL Java_com_lengyue524_opus_OpusEncoder_init_1restricted_1low_1delay_1native
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lengyue524_opus_OpusEncoder
 * Method:    encode_native
 * Signature: (I[S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_lengyue524_opus_OpusEncoder_encode_1native
  (JNIEnv *, jobject, jlong, jshortArray, jint);

/*
 * Class:     com_lengyue524_opus_OpusEncoder
 * Method:    destory_native
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lengyue524_opus_OpusEncoder_destory_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
