/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lengyue524_opus_android_opus_OpusDecoder */

#ifndef _Included_com_lengyue524_opus_android_opus_OpusDecoder
#define _Included_com_lengyue524_opus_android_opus_OpusDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lengyue524_opus_android_opus_OpusDecoder
 * Method:    init_native
 * Signature: (II)I
 */
JNIEXPORT jlong JNICALL Java_com_lengyue524_opus_1android_opus_OpusDecoder_init_1native
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lengyue524_opus_android_opus_OpusDecoder
 * Method:    decode_native
 * Signature: (I[B)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_lengyue524_opus_1android_opus_OpusDecoder_decode_1native
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     com_lengyue524_opus_android_opus_OpusDecoder
 * Method:    destory_native
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_lengyue524_opus_1android_opus_OpusDecoder_destory_1native
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
